---
title: "porphyromonas_task"
author: "ISonetz"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = FALSE,
                      cache = TRUE)
library("phyloseq")
library("ggplot2")      
library("readxl")      
library("dplyr")        
library("tibble") 
library("vegan")
library("scales")
library("microbiome")
library("hrbrthemes")
library("gcookbook")
library("tidyverse")
library('speedyseq')
```

## Analysis of WGS Porphyromonas data made with Phyloseq

```{r reading data and creating phyloseq object}
otu_count_df<- read.csv("../metaphlan_count_df.csv", sep='\t')
taxa_df<- read.csv("../metaphlan_taxa_df.csv", sep='\t')
samples_df <- read.csv("../metaphlan_full_metadata_mod2.csv", sep=',')
# NA filling for empty values in samples metadata df
samples_df <- samples_df %>% mutate(across(everything(), ~ifelse(.=="", NA, as.character(.))))
# remaking date column
# UPD 18/11/24: skip for now, smth wrong during conversion
#samples_df[['Дата.забора.образца']] <- strptime(samples_df[['Дата.забора.образца']], format = "%d/%m/%y")

# making age column as factor
samples_df$Возраст = cut(as.numeric(samples_df$Возраст), breaks = 4, 
                         labels = c ('(36-45.2]', '(45.2-54.5]', '(54.5-63.8]', '(63.8-73]'))
# non_numeric_cols <- sapply(samples_df, is.character)
# samples_df[non_numeric_cols] <- lapply(samples_df[non_numeric_cols==TRUE], as.factor)
# remove underscore to reach consistency in sample IDs
samples_df$Вес <- as.numeric(samples_df$Вес)
samples_df$Рост <- as.numeric(samples_df$Рост)
colnames(otu_count_df)<-gsub("_","",colnames(otu_count_df))
```

```{r creating phyloseq}
# defining row names
otu_count_df <- otu_count_df %>%
  tibble::column_to_rownames("OTU") 
samples_df <- samples_df %>% 
  tibble::column_to_rownames("ID") 
taxa_df <- taxa_df %>% 
  tibble::column_to_rownames("OTU")
otu_count_df <- as.matrix(otu_count_df)
taxa_df <- as.matrix(taxa_df)
# creating phyloseq
OTU = otu_table(otu_count_df, taxa_are_rows = TRUE)
TAX = tax_table(taxa_df)
SAMPLES = sample_data(samples_df)
ps_phyloseq <- phyloseq(OTU, TAX, SAMPLES)
#create sample id
ps_phyloseq@sam_data$sample_id <- row.names(ps_phyloseq@sam_data)
# UPD 18/11/24: create BMI column just for fun
#ps_phyloseq@sam_data$BMI <- ps_phyloseq@sam_data$Вес/((ps_phyloseq@sam_data$Рост/100)**2)
```

```{r remembering functions}
#simple calc failed, both have NAs, so we need to do it with function
calculate_bmi <- function(weight, height) {
  if (is.na(weight) || is.na(height)) {
    return(NA)  # Skip calculation if either value is NA
  } else {
    bmi <- weight / ((height/100)^2)  # Calculate BMI only if both values are provided
    return(bmi)
  }
}
ps_phyloseq@sam_data$BMI <- mapply(calculate_bmi, ps_phyloseq@sam_data$Вес, ps_phyloseq@sam_data$Рост)
```

```{r cleaning phyloseq obj}
# removing 't__' from Strain
tax <- as.data.frame(as.matrix(ps_phyloseq@tax_table)) 
tax$Strain <- gsub('t__','',tax$Strain)
ps_phyloseq@tax_table <-  tax_table((as.matrix(tax)))
# filtering euk/archaea
ps_phyloseq <- subset_taxa(ps_phyloseq, !Species %in% c("None") & !Phylum %in% c('Eukaryota','Archaea'))
```

```{r sample data plot, dev = 'png', fig.width=15, fig.height=10}
ps_obj <- ps_phyloseq # copy of original phyloseq obj

df <- as.data.frame(as.matrix(ps_obj@sam_data))

cols_to_keep <- c("Возраст","Пол", "Вес",'Артериальная.гипертензия','СД', "Стадия.тяжести.пародонтита", 'Курение.в.настоящее.время', "PCR.RT..Гингипол..Литех.Porphyromonas.gingivalis", "Как.давно.бросил.курить", 'АБ.за.полгода') # for example

df_f <- select(df, all_of(cols_to_keep))

df_long <- df_f %>%
  pivot_longer(cols = everything(), names_to = "Column_Name", values_to = "Value")
size=10
# Create a count plot
ggplot(df_long, aes(x = Value,fill=Value)) +
  geom_bar() +
  facet_wrap(~ Column_Name, scales = "free")  +
  labs(title = "Count Plot", x = "Value", y = "Count") + theme(
    axis.text.y = element_text(color = "black", size = size),
    axis.text.x = element_text(angle=90, hjust=1,size=size,color = 'black'),
    legend.position = "right",
    axis.title.y  = element_text(color = "black", size = size,angle=90),
    axis.title.x  = element_text(color = "black", size = size),
    #legend.key.size = unit(0.5, 'cm'),
    #plot.title = element_text(hjust = 0.5,size =size),
    text = element_text(size = size,colour ='black' ),
    # Set panel background to white
    panel.border = element_rect(fill = NA, color = "black"),
     panel.background = element_rect(fill = "white", colour = "black"),
    panel.grid.major = element_line(size = 0.1, linetype = 'solid',
                                colour = "gray"), 
  panel.grid.minor = element_line(size = 0.1, linetype = 'solid',
                                colour = "gray")) 
df$df_sample <- row.names(df)
```

```{r some testing plots and transformation, dev='png', fig.width=15, fig.height=10}
ps_obj <- ps_phyloseq # copy of original phyloseq 
ps_obj
ps_obj <- subset_samples(ps_phyloseq, Стадия.тяжести.пародонтита  =="средняя" & Пол == 'м')
# store only species for which strain data is available
ps_obj <- subset_taxa(ps_obj, Strain != 'None')
ps_obj
# agglom up to genus rank
ps_obj <- speedyseq::tax_glom(ps_obj,taxrank = 'Genus', NArm=T ) # speedyseq пакет для филосека с быстрыми функциями
ps_obj
# relative abundance and transformation, as in https://microbiome.github.io/tutorials/
det <- 1
prev<-50/100
taxas <- core_members(ps_obj, detection = det, prevalence = prev)
ps_obj <- prune_taxa(taxas, ps_obj)
ps_obj
transformation <- 'compositional'
ps_obj <- microbiome::transform(ps_obj, transformation)
# simple rel.abundance plot
plot_bar(ps_obj, fill = "Genus",title = "Relative abundance data, Genus level")
```

```{r relative abundance v2, dev='png', fig.width=15, fig.height=10}
# using microbiome pkg
#scale_color_brewer has too small colors, instead use standard gradient palette
p <- plot_composition(ps_obj,
                      taxonomic.level = "Genus",
                      x.label = "sample_id") +
  guides(fill = guide_legend(ncol = 1)) +
  scale_y_percent() +
  labs(x = "Samples", y = "Relative abundance (%)",
       title = "Relative abundance data, Genus level") + 
  theme_ipsum(grid="Y") +
  theme(axis.text.x = element_text(angle=90, hjust=1),
        legend.text = element_text(face = "italic"))
print(p)
# this plot works
```

```{r subset 50+yrs and weight <=70 kg,dev='png', fig.width=15, fig.height=10}
ps_obj <- subset_samples(ps_phyloseq, Вес<=70 & Возраст %in% c('(54.5-63.8]','(63.8-73]'))
# agglom up to family rank
ps_obj <- speedyseq::tax_glom(ps_subset_50yr_70kg,taxrank = 'Family', NArm=T )
det <- 1
prev<-50/100
taxas <- core_members(ps_obj, detection = det, prevalence = prev)
ps_obj <- prune_taxa(taxas, ps_obj)
ps_obj
transformation <- 'compositional'
ps_obj <- microbiome::transform(ps_obj, transformation)
plot_bar(ps_obj, fill = "Family", title = "Relative abundance data for 50+yrs \nadults less than 70 kg weight, Family level")
```


```{r subset 50+yrs and weight <=70 kg plot v2,dev='png', fig.width=15, fig.height=10}
p <- plot_composition(ps_obj,
                      taxonomic.level = "Family",
                      x.label = "sample_id") +
  guides(fill = guide_legend(ncol = 1)) +
  scale_y_percent() +
  labs(x = "Samples", y = "Relative abundance (%)",
       title = "Relative abundance data for 50+yrs \nadults less than 70 kg weight, Family level") + 
  theme_ipsum(grid="Y") +
  theme(axis.text.x = element_text(angle=90, hjust=1),
        legend.text = element_text(face = "italic"))
print(p)
```

```{r how to get normal taxa names, dev='png', fig.width=15, fig.height=10 }
# normal taxa names are stored in ps_obj@tax_table[,5] for Family, for example
# we should use scale_fill_manual, I suppose, but couldn't get it work
# I think it should be smth like this?
# earlier we already agglomerated by Family, in theory it should be enough, but NOPE.
p <- plot_composition(ps_obj,
                      taxonomic.level = "Family",
                      x.label = "sample_id") +
  scale_y_percent() +
  labs(x = "Samples", y = "Relative abundance (%)",
       title = "Relative abundance data for 50+yrs \nadults less than 70 kg weight, Family level") + 
  theme_ipsum(grid="Y") +
  theme(axis.text.x = element_text(angle=90, hjust=1),
        legend.text = element_text(face = "italic")) + 
  scale_fill_manual(values=default_colors("Family")[as.vector(ps_obj@tax_table[,5])])
```

```{r species, dev='png', fig.width=15, fig.height=10 }
ps_obj <- ps_phyloseq
ps_obj <- speedyseq::tax_glom(ps_obj,taxrank = 'Species', NArm=T )
det <- 1
prev<-50/100
taxas <- core_members(ps_obj, detection = det, prevalence = prev)
ps_obj <- prune_taxa(taxas, ps_obj)
ps_obj
transformation <- 'compositional'
ps_obj <- microbiome::transform(ps_obj, transformation)
plot_bar(ps_obj, fill = "Species",title = "Relative abundance data, Species level, core members, compositional transformation")
```

```{r top 15 species, dev='png', fig.width=15, fig.height=10 }
# what if top 15 species?
ps_obj <- ps_phyloseq
ps_obj <- speedyseq::tax_glom(ps_obj,taxrank = 'Species', NArm=T )
ps_obj_top10_names <- names(sort(taxa_sums(ps_obj), TRUE)[1:15]) 
#ps_obj_tops<- transform_sample_counts(ps_obj, function(s) s/sum(s))
ps_obj_top10<-prune_taxa(ps_obj_top10_names, ps_obj )
ps_obj_top10 <- transform_sample_counts(ps_obj_top10, function(x) x / sum(x))
plot_bar(ps_obj_top10, fill='Species', title= 'Top 15 species across all samples')
```
